apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: nginx
          startupProbe:
            httpGet:
              path: /api/health
          readinessProbe:
            httpGet:
              path: /api/health
          livenessProbe:
            httpGet:
              path: /api/health
